@echo off

"pvengine.exe" +W1600 +H1200 +FN +L"c:/windows/fonts" +L"/Users/pcavenel-SSD/Documents/PERSO/TRAIN_ELECTRIQUE/RESEAU_BARRAUX/DEVELOPPEMENT_BOARD_CAN/RAIL_DRIVER_V1.2/3D_RENDERING/eagle3d/ulp//../povray" +O"/Users/pcavenel-SSD/Documents/PERSO/TRAIN_ELECTRIQUE/RESEAU_BARRAUX/DEVELOPPEMENT_BOARD_CAN/RAIL_DRIVER_V1.2/EAGLE_FILES/RailDriver/RailDriver.png" /RENDER "/Users/pcavenel-SSD/Documents/PERSO/TRAIN_ELECTRIQUE/RESEAU_BARRAUX/DEVELOPPEMENT_BOARD_CAN/RAIL_DRIVER_V1.2/EAGLE_FILES/RailDriver/RailDriver.pov" 
